### ISSUE TITLE
Question about style

### ISSUE THREAD

**Issue by asystentka-jolka** [bradcrc/Now-Playing-Card#1]
Hi, great work :) 

i'm trying to move the image around my floorplan something like in your example
```
 - type: "custom:now-playing-poster"
   entity: media_player.my_player  
   style:
     width: 10%
     top: 20%
     left: 9%
```

I'm not able to style the card (move the card on the view background).
Do you use something special / additional to style the card? Like https://github.com/thomasloven/lovelace-card-mod maybe?

Thanks in advance for your answer :+1:
